### PR TITLE
Update Submodules

### PR DESCRIPTION
**Pull request by viper-admin**
* Updates Gobra from `a1d44244a0fec82d3595e055d9246217db935fe6` to `a0bc98f078ed714fcb759b92532d2e10b77d81c7`.

### CODE REVIEW

**Comment by viper-admin** [comment]
bors merge

**Comment by viper-admin** [comment]
bors merge

**Comment by viper-admin** [comment]
bors merge

**Comment by viper-admin** [comment]
bors merge

**Comment by viper-admin** [comment]
bors merge

**Comment by viper-admin** [comment]
bors merge

**Comment by viper-admin** [comment]
bors merge

**Comment by viper-admin** [comment]
bors merge

**Comment by ArquintL** [comment]
bors merge

**Pull request closed without merging**
